stages :
    - build
    - deploy
build_staging :
    stage: build
    script:
          - source /etc/profile
          - echo "java Build..."
          ##- cd projects/star-user/
          - mvn clean package -U -P test -Dmaven.test.skip=true
          - rsync -av target/star-user.war webserver@192.168.31.236:~/star-user/
          - ssh webserver@192.168.31.236  "source /etc/profile;cd ~/star-user;rm -rf bak.webapp && mv -f webapp bak.webapp;unzip star-user.war -d webapp;./restart.sh"
    only :
        - dev
    tags :
        - java-shell
deploy_fabo :
    stage : deploy
    script :
        ##- md5sum target/star-user.war |awk '{print $1}' > target/star-user.war.md5
        - /opt/ci-shell/2.0/to-git --rsync-from=target/star-user.wa*  --git-repository=online/aiwan.user.api.com.git  --clean=false
    only :
        - master
    tags :
        - java-shell
    